-- =====================================================================
-- UCC Pasto 3D - Esquema de base de datos (PostgreSQL)
-- Este repositorio es la ÚNICA fuente de verdad del modelo de datos.
-- =====================================================================

CREATE TABLE IF NOT EXISTS edificio (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(20)  NOT NULL UNIQUE,
    nombre          VARCHAR(120) NOT NULL,
    descripcion     TEXT,
    pos_x           DOUBLE PRECISION NOT NULL DEFAULT 0,  -- posición en el mapa 3D (metros)
    pos_z           DOUBLE PRECISION NOT NULL DEFAULT 0,
    ancho           DOUBLE PRECISION NOT NULL DEFAULT 10,
    profundidad     DOUBLE PRECISION NOT NULL DEFAULT 10,
    pisos           INTEGER      NOT NULL DEFAULT 1,
    sotanos         INTEGER      NOT NULL DEFAULT 0,  -- pisos subterráneos
    color           VARCHAR(9)   NOT NULL DEFAULT '#cfd8dc',
    tipo            VARCHAR(30)  NOT NULL DEFAULT 'EDIFICIO' -- EDIFICIO, ZONA_VERDE, PARQUEADERO, DEPORTIVO
);

CREATE TABLE IF NOT EXISTS lugar (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(150) NOT NULL,
    tipo            VARCHAR(40)  NOT NULL,  -- OFICINA, LABORATORIO, AULA, SERVICIO, CLINICA
    edificio_id     INTEGER      NOT NULL REFERENCES edificio(id),
    piso            INTEGER      NOT NULL DEFAULT 1,  -- negativo = sótano (-1 = sótano 1)
    descripcion     TEXT,
    horario         VARCHAR(150),
    telefono        VARCHAR(60),
    correo          VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS programa (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(150) NOT NULL,
    facultad            VARCHAR(150) NOT NULL,
    nivel               VARCHAR(30)  NOT NULL,  -- PREGRADO, ESPECIALIZACION, MAESTRIA, TECNICO
    modalidad           VARCHAR(30)  NOT NULL DEFAULT 'PRESENCIAL',
    duracion_semestres  INTEGER,
    titulo              VARCHAR(150),
    descripcion         TEXT,
    edificio_id         INTEGER REFERENCES edificio(id)
);

CREATE TABLE IF NOT EXISTS pregunta_frecuente (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria       VARCHAR(60)  NOT NULL,
    pregunta        VARCHAR(300) NOT NULL,
    respuesta       TEXT         NOT NULL,
    palabras_clave  VARCHAR(300)            -- separadas por coma, ayudan al asistente local
);

CREATE TABLE IF NOT EXISTS conversacion (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pregunta        TEXT         NOT NULL,
    respuesta       TEXT         NOT NULL,
    proveedor       VARCHAR(40)  NOT NULL,
    creado_en       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Para bases ya creadas antes de agregar sótanos
ALTER TABLE edificio ADD COLUMN IF NOT EXISTS sotanos INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_lugar_edificio    ON lugar(edificio_id);
CREATE INDEX IF NOT EXISTS idx_programa_edificio ON programa(edificio_id);


